INSERT INTO CAR_NAMES VALUES (1, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO CAR_NAMES VALUES (2, 'buick', 'buick skylark 320');
INSERT INTO CAR_NAMES VALUES (3, 'plymouth', 'plymouth satellite');
INSERT INTO CAR_NAMES VALUES (4, 'amc', 'amc rebel sst');
INSERT INTO CAR_NAMES VALUES (5, 'ford', 'ford torino');
INSERT INTO CAR_NAMES VALUES (6, 'ford', 'ford galaxie 500');
INSERT INTO CAR_NAMES VALUES (7, 'chevrolet', 'chevrolet impala');
INSERT INTO CAR_NAMES VALUES (8, 'plymouth', 'plymouth fury iii');
INSERT INTO CAR_NAMES VALUES (9, 'pontiac', 'pontiac catalina');
INSERT INTO CAR_NAMES VALUES (10, 'amc', 'amc ambassador dpl');
INSERT INTO CAR_NAMES VALUES (11, 'citroen', 'citroen ds-21 pallas');
INSERT INTO CAR_NAMES VALUES (12, 'chevrolet', 'chevrolet chevelle concours (sw)');
INSERT INTO CAR_NAMES VALUES (13, 'ford', 'ford torino (sw)');
INSERT INTO CAR_NAMES VALUES (14, 'plymouth', 'plymouth satellite (sw)');
INSERT INTO CAR_NAMES VALUES (15, 'amc', 'amc rebel sst (sw)');
INSERT INTO CAR_NAMES VALUES (16, 'dodge', 'dodge challenger se');
INSERT INTO CAR_NAMES VALUES (17, 'plymouth', 'plymouth cuda 340');
INSERT INTO CAR_NAMES VALUES (18, 'ford', 'ford mustang boss 302');
INSERT INTO CAR_NAMES VALUES (19, 'chevrolet', 'chevrolet monte carlo');
INSERT INTO CAR_NAMES VALUES (20, 'buick', 'buick estate wagon (sw)');
INSERT INTO CAR_NAMES VALUES (21, 'toyota', 'toyota corona mark ii');
INSERT INTO CAR_NAMES VALUES (22, 'plymouth', 'plymouth duster');
INSERT INTO CAR_NAMES VALUES (23, 'amc', 'amc hornet');
INSERT INTO CAR_NAMES VALUES (24, 'ford', 'ford maverick');
INSERT INTO CAR_NAMES VALUES (25, 'datsun', 'datsun pl510');
INSERT INTO CAR_NAMES VALUES (26, 'volkswagen', 'volkswagen 1131 deluxe sedan');
INSERT INTO CAR_NAMES VALUES (27, 'peugeot', 'peugeot 504');
INSERT INTO CAR_NAMES VALUES (28, 'audi', 'audi 100 ls');
INSERT INTO CAR_NAMES VALUES (29, 'saab', 'saab 99e');
INSERT INTO CAR_NAMES VALUES (30, 'bmw', 'bmw 2002');
INSERT INTO CAR_NAMES VALUES (31, 'amc', 'amc gremlin');
INSERT INTO CAR_NAMES VALUES (32, 'ford', 'ford f250');
INSERT INTO CAR_NAMES VALUES (33, 'chevrolet', 'chevy c20');
INSERT INTO CAR_NAMES VALUES (34, 'dodge', 'dodge d200');
INSERT INTO CAR_NAMES VALUES (35, 'hi', 'hi 1200d');
INSERT INTO CAR_NAMES VALUES (36, 'datsun', 'datsun pl510');
INSERT INTO CAR_NAMES VALUES (37, 'chevrolet', 'chevrolet vega 2300');
INSERT INTO CAR_NAMES VALUES (38, 'toyota', 'toyota corona');
INSERT INTO CAR_NAMES VALUES (39, 'ford', 'ford pinto');
INSERT INTO CAR_NAMES VALUES (40, 'volkswagen', 'volkswagen super beetle 117');
INSERT INTO CAR_NAMES VALUES (41, 'amc', 'amc gremlin');
INSERT INTO CAR_NAMES VALUES (42, 'plymouth', 'plymouth satellite custom');
INSERT INTO CAR_NAMES VALUES (43, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO CAR_NAMES VALUES (44, 'ford', 'ford torino 500');
INSERT INTO CAR_NAMES VALUES (45, 'amc', 'amc matador');
INSERT INTO CAR_NAMES VALUES (46, 'chevrolet', 'chevrolet impala');
INSERT INTO CAR_NAMES VALUES (47, 'pontiac', 'pontiac catalina brougham');
INSERT INTO CAR_NAMES VALUES (48, 'ford', 'ford galaxie 500');
INSERT INTO CAR_NAMES VALUES (49, 'plymouth', 'plymouth fury iii');
INSERT INTO CAR_NAMES VALUES (50, 'dodge', 'dodge monaco (sw)');
INSERT INTO CAR_NAMES VALUES (51, 'ford', 'ford country squire (sw)');
INSERT INTO CAR_NAMES VALUES (52, 'pontiac', 'pontiac safari (sw)');
INSERT INTO CAR_NAMES VALUES (53, 'amc', 'amc hornet sportabout (sw)');
INSERT INTO CAR_NAMES VALUES (54, 'chevrolet', 'chevrolet vega (sw)');
INSERT INTO CAR_NAMES VALUES (55, 'pontiac', 'pontiac firebird');
INSERT INTO CAR_NAMES VALUES (56, 'ford', 'ford mustang');
INSERT INTO CAR_NAMES VALUES (57, 'mercury', 'mercury capri 2000');
INSERT INTO CAR_NAMES VALUES (58, 'opel', 'opel 1900');
INSERT INTO CAR_NAMES VALUES (59, 'peugeot', 'peugeot 304');
INSERT INTO CAR_NAMES VALUES (60, 'fiat', 'fiat 124b');
INSERT INTO CAR_NAMES VALUES (61, 'toyota', 'toyota corolla 1200');
INSERT INTO CAR_NAMES VALUES (62, 'datsun', 'datsun 1200');
INSERT INTO CAR_NAMES VALUES (63, 'volkswagen', 'volkswagen model 111');
INSERT INTO CAR_NAMES VALUES (64, 'plymouth', 'plymouth cricket');
INSERT INTO CAR_NAMES VALUES (65, 'toyota', 'toyota corona hardtop');
INSERT INTO CAR_NAMES VALUES (66, 'dodge', 'dodge colt hardtop');
INSERT INTO CAR_NAMES VALUES (67, 'volkswagen', 'volkswagen type 3');
INSERT INTO CAR_NAMES VALUES (68, 'chevrolet', 'chevrolet vega');
INSERT INTO CAR_NAMES VALUES (69, 'ford', 'ford pinto runabout');
INSERT INTO CAR_NAMES VALUES (70, 'chevrolet', 'chevrolet impala');
INSERT INTO CAR_NAMES VALUES (71, 'pontiac', 'pontiac catalina');
INSERT INTO CAR_NAMES VALUES (72, 'plymouth', 'plymouth fury iii');
INSERT INTO CAR_NAMES VALUES (73, 'ford', 'ford galaxie 500');
INSERT INTO CAR_NAMES VALUES (74, 'amc', 'amc ambassador sst');
INSERT INTO CAR_NAMES VALUES (75, 'mercury', 'mercury marquis');
INSERT INTO CAR_NAMES VALUES (76, 'buick', 'buick lesabre custom');
INSERT INTO CAR_NAMES VALUES (77, 'oldsmobile', 'oldsmobile delta 88 royale');
INSERT INTO CAR_NAMES VALUES (78, 'chrysler', 'chrysler newport royal');
INSERT INTO CAR_NAMES VALUES (79, 'mazda', 'mazda rx2 coupe');
INSERT INTO CAR_NAMES VALUES (80, 'amc', 'amc matador (sw)');
INSERT INTO CAR_NAMES VALUES (81, 'chevrolet', 'chevrolet chevelle concours (sw)');
INSERT INTO CAR_NAMES VALUES (82, 'ford', 'ford gran torino (sw)');
INSERT INTO CAR_NAMES VALUES (83, 'plymouth', 'plymouth satellite custom (sw)');
INSERT INTO CAR_NAMES VALUES (84, 'volvo', 'volvo 145e (sw)');
INSERT INTO CAR_NAMES VALUES (85, 'volkswagen', 'volkswagen 411 (sw)');
INSERT INTO CAR_NAMES VALUES (86, 'peugeot', 'peugeot 504 (sw)');
INSERT INTO CAR_NAMES VALUES (87, 'renault', 'renault 12 (sw)');
INSERT INTO CAR_NAMES VALUES (88, 'ford', 'ford pinto (sw)');
INSERT INTO CAR_NAMES VALUES (89, 'datsun', 'datsun 510 (sw)');
INSERT INTO CAR_NAMES VALUES (90, 'toyota', 'toyota corona mark ii (sw)');
INSERT INTO CAR_NAMES VALUES (91, 'dodge', 'dodge colt (sw)');
INSERT INTO CAR_NAMES VALUES (92, 'toyota', 'toyota corolla 1600 (sw)');
INSERT INTO CAR_NAMES VALUES (93, 'buick', 'buick century 350');
INSERT INTO CAR_NAMES VALUES (94, 'amc', 'amc matador');
INSERT INTO CAR_NAMES VALUES (95, 'chevrolet', 'chevrolet malibu');
INSERT INTO CAR_NAMES VALUES (96, 'ford', 'ford gran torino');
INSERT INTO CAR_NAMES VALUES (97, 'dodge', 'dodge coronet custom');
INSERT INTO CAR_NAMES VALUES (98, 'mercury', 'mercury marquis brougham');
INSERT INTO CAR_NAMES VALUES (99, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO CAR_NAMES VALUES (100, 'ford', 'ford ltd');
INSERT INTO CAR_NAMES VALUES (101, 'plymouth', 'plymouth fury gran sedan');
INSERT INTO CAR_NAMES VALUES (102, 'chrysler', 'chrysler new yorker brougham');
INSERT INTO CAR_NAMES VALUES (103, 'buick', 'buick electra 225 custom');
INSERT INTO CAR_NAMES VALUES (104, 'amc', 'amc ambassador brougham');
INSERT INTO CAR_NAMES VALUES (105, 'plymouth', 'plymouth valiant');
INSERT INTO CAR_NAMES VALUES (106, 'chevrolet', 'chevrolet nova custom');
INSERT INTO CAR_NAMES VALUES (107, 'amc', 'amc hornet');
INSERT INTO CAR_NAMES VALUES (108, 'ford', 'ford maverick');
INSERT INTO CAR_NAMES VALUES (109, 'plymouth', 'plymouth duster');
INSERT INTO CAR_NAMES VALUES (110, 'volkswagen', 'volkswagen super beetle');
INSERT INTO CAR_NAMES VALUES (111, 'chevrolet', 'chevrolet impala');
INSERT INTO CAR_NAMES VALUES (112, 'ford', 'ford country');
INSERT INTO CAR_NAMES VALUES (113, 'plymouth', 'plymouth custom suburb');
INSERT INTO CAR_NAMES VALUES (114, 'oldsmobile', 'oldsmobile vista cruiser');
INSERT INTO CAR_NAMES VALUES (115, 'amc', 'amc gremlin');
INSERT INTO CAR_NAMES VALUES (116, 'toyota', 'toyota carina');
INSERT INTO CAR_NAMES VALUES (117, 'chevrolet', 'chevrolet vega');
INSERT INTO CAR_NAMES VALUES (118, 'datsun', 'datsun 610');
INSERT INTO CAR_NAMES VALUES (119, 'mazda', 'mazda rx3');
INSERT INTO CAR_NAMES VALUES (120, 'ford', 'ford pinto');
INSERT INTO CAR_NAMES VALUES (121, 'mercury', 'mercury capri v6');
INSERT INTO CAR_NAMES VALUES (122, 'fiat', 'fiat 124 sport coupe');
INSERT INTO CAR_NAMES VALUES (123, 'chevrolet', 'chevrolet monte carlo s');
INSERT INTO CAR_NAMES VALUES (124, 'pontiac', 'pontiac grand prix');
INSERT INTO CAR_NAMES VALUES (125, 'fiat', 'fiat 128');
INSERT INTO CAR_NAMES VALUES (126, 'opel', 'opel manta');
INSERT INTO CAR_NAMES VALUES (127, 'audi', 'audi 100ls');
INSERT INTO CAR_NAMES VALUES (128, 'volvo', 'volvo 144ea');
INSERT INTO CAR_NAMES VALUES (129, 'dodge', 'dodge dart custom');
INSERT INTO CAR_NAMES VALUES (130, 'saab', 'saab 99le');
INSERT INTO CAR_NAMES VALUES (131, 'toyota', 'toyota mark ii');
INSERT INTO CAR_NAMES VALUES (132, 'oldsmobile', 'oldsmobile omega');
INSERT INTO CAR_NAMES VALUES (133, 'plymouth', 'plymouth duster');
INSERT INTO CAR_NAMES VALUES (134, 'ford', 'ford maverick');
INSERT INTO CAR_NAMES VALUES (135, 'amc', 'amc hornet');
INSERT INTO CAR_NAMES VALUES (136, 'chevrolet', 'chevrolet nova');
INSERT INTO CAR_NAMES VALUES (137, 'datsun', 'datsun b210');
INSERT INTO CAR_NAMES VALUES (138, 'ford', 'ford pinto');
INSERT INTO CAR_NAMES VALUES (139, 'toyota', 'toyota corolla 1200');
INSERT INTO CAR_NAMES VALUES (140, 'chevrolet', 'chevrolet vega');
INSERT INTO CAR_NAMES VALUES (141, 'chevrolet', 'chevrolet chevelle malibu classic');
INSERT INTO CAR_NAMES VALUES (142, 'amc', 'amc matador');
INSERT INTO CAR_NAMES VALUES (143, 'plymouth', 'plymouth satellite sebring');
INSERT INTO CAR_NAMES VALUES (144, 'ford', 'ford gran torino');
INSERT INTO CAR_NAMES VALUES (145, 'buick', 'buick century luxus (sw)');
INSERT INTO CAR_NAMES VALUES (146, 'dodge', 'dodge coronet custom (sw)');
INSERT INTO CAR_NAMES VALUES (147, 'ford', 'ford gran torino (sw)');
INSERT INTO CAR_NAMES VALUES (148, 'amc', 'amc matador (sw)');
INSERT INTO CAR_NAMES VALUES (149, 'audi', 'audi fox');
INSERT INTO CAR_NAMES VALUES (150, 'volkswagen', 'volkswagen dasher');
INSERT INTO CAR_NAMES VALUES (151, 'opel', 'opel manta');
INSERT INTO CAR_NAMES VALUES (152, 'toyota', 'toyota corona');
INSERT INTO CAR_NAMES VALUES (153, 'datsun', 'datsun 710');
INSERT INTO CAR_NAMES VALUES (154, 'dodge', 'dodge colt');
INSERT INTO CAR_NAMES VALUES (155, 'fiat', 'fiat 128');
INSERT INTO CAR_NAMES VALUES (156, 'fiat', 'fiat 124 tc');
INSERT INTO CAR_NAMES VALUES (157, 'honda', 'honda civic');
INSERT INTO CAR_NAMES VALUES (158, 'subaru', 'subaru');
INSERT INTO CAR_NAMES VALUES (159, 'fiat', 'fiat x1.9');
INSERT INTO CAR_NAMES VALUES (160, 'plymouth', 'plymouth valiant custom');
INSERT INTO CAR_NAMES VALUES (161, 'chevrolet', 'chevrolet nova');
INSERT INTO CAR_NAMES VALUES (162, 'mercury', 'mercury monarch');
INSERT INTO CAR_NAMES VALUES (163, 'ford', 'ford maverick');
INSERT INTO CAR_NAMES VALUES (164, 'pontiac', 'pontiac catalina');
INSERT INTO CAR_NAMES VALUES (165, 'chevrolet', 'chevrolet bel air');
INSERT INTO CAR_NAMES VALUES (166, 'plymouth', 'plymouth grand fury');
INSERT INTO CAR_NAMES VALUES (167, 'ford', 'ford ltd');
INSERT INTO CAR_NAMES VALUES (168, 'buick', 'buick century');
INSERT INTO CAR_NAMES VALUES (169, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO CAR_NAMES VALUES (170, 'amc', 'amc matador');
INSERT INTO CAR_NAMES VALUES (171, 'plymouth', 'plymouth fury');
INSERT INTO CAR_NAMES VALUES (172, 'buick', 'buick skyhawk');
INSERT INTO CAR_NAMES VALUES (173, 'chevrolet', 'chevrolet monza 2+2');
INSERT INTO CAR_NAMES VALUES (174, 'ford', 'ford mustang ii');
INSERT INTO CAR_NAMES VALUES (175, 'toyota', 'toyota corolla');
INSERT INTO CAR_NAMES VALUES (176, 'ford', 'ford pinto');
INSERT INTO CAR_NAMES VALUES (177, 'amc', 'amc gremlin');
INSERT INTO CAR_NAMES VALUES (178, 'pontiac', 'pontiac astro');
INSERT INTO CAR_NAMES VALUES (179, 'toyota', 'toyota corona');
INSERT INTO CAR_NAMES VALUES (180, 'volkswagen', 'volkswagen dasher');
INSERT INTO CAR_NAMES VALUES (181, 'datsun', 'datsun 710');
INSERT INTO CAR_NAMES VALUES (182, 'ford', 'ford pinto');
INSERT INTO CAR_NAMES VALUES (183, 'volkswagen', 'volkswagen rabbit');
INSERT INTO CAR_NAMES VALUES (184, 'amc', 'amc pacer');
INSERT INTO CAR_NAMES VALUES (185, 'audi', 'audi 100ls');
INSERT INTO CAR_NAMES VALUES (186, 'peugeot', 'peugeot 504');
INSERT INTO CAR_NAMES VALUES (187, 'volvo', 'volvo 244dl');
INSERT INTO CAR_NAMES VALUES (188, 'saab', 'saab 99le');
INSERT INTO CAR_NAMES VALUES (189, 'honda', 'honda civic cvcc');
INSERT INTO CAR_NAMES VALUES (190, 'fiat', 'fiat 131');
INSERT INTO CAR_NAMES VALUES (191, 'opel', 'opel 1900');
INSERT INTO CAR_NAMES VALUES (192, 'capri', 'capri ii');
INSERT INTO CAR_NAMES VALUES (193, 'dodge', 'dodge colt');
INSERT INTO CAR_NAMES VALUES (194, 'renault', 'renault 12tl');
INSERT INTO CAR_NAMES VALUES (195, 'chevrolet', 'chevrolet chevelle malibu classic');
INSERT INTO CAR_NAMES VALUES (196, 'dodge', 'dodge coronet brougham');
INSERT INTO CAR_NAMES VALUES (197, 'amc', 'amc matador');
INSERT INTO CAR_NAMES VALUES (198, 'ford', 'ford gran torino');
INSERT INTO CAR_NAMES VALUES (199, 'plymouth', 'plymouth valiant');
INSERT INTO CAR_NAMES VALUES (200, 'chevrolet', 'chevrolet nova');
INSERT INTO CAR_NAMES VALUES (201, 'ford', 'ford maverick');
INSERT INTO CAR_NAMES VALUES (202, 'amc', 'amc hornet');
INSERT INTO CAR_NAMES VALUES (203, 'chevrolet', 'chevrolet chevette');
INSERT INTO CAR_NAMES VALUES (204, 'chevrolet', 'chevrolet woody');
INSERT INTO CAR_NAMES VALUES (205, 'volkswagen', 'vw rabbit');
INSERT INTO CAR_NAMES VALUES (206, 'honda', 'honda civic');
INSERT INTO CAR_NAMES VALUES (207, 'dodge', 'dodge aspen se');
INSERT INTO CAR_NAMES VALUES (208, 'ford', 'ford granada ghia');
INSERT INTO CAR_NAMES VALUES (209, 'pontiac', 'pontiac ventura sj');
INSERT INTO CAR_NAMES VALUES (210, 'amc', 'amc pacer d/l');
INSERT INTO CAR_NAMES VALUES (211, 'volkswagen', 'volkswagen rabbit');
INSERT INTO CAR_NAMES VALUES (212, 'datsun', 'datsun b-210');
INSERT INTO CAR_NAMES VALUES (213, 'toyota', 'toyota corolla');
INSERT INTO CAR_NAMES VALUES (214, 'ford', 'ford pinto');
INSERT INTO CAR_NAMES VALUES (215, 'volvo', 'volvo 245');
INSERT INTO CAR_NAMES VALUES (216, 'plymouth', 'plymouth volare premier v8');
INSERT INTO CAR_NAMES VALUES (217, 'peugeot', 'peugeot 504');
INSERT INTO CAR_NAMES VALUES (218, 'toyota', 'toyota mark ii');
INSERT INTO CAR_NAMES VALUES (219, 'mercedes-benz', 'mercedes-benz 280s');
INSERT INTO CAR_NAMES VALUES (220, 'cadillac', 'cadillac seville');
INSERT INTO CAR_NAMES VALUES (221, 'chevrolet', 'chevy c10');
INSERT INTO CAR_NAMES VALUES (222, 'ford', 'ford f108');
INSERT INTO CAR_NAMES VALUES (223, 'dodge', 'dodge d100');
INSERT INTO CAR_NAMES VALUES (224, 'honda', 'honda accord cvcc');
INSERT INTO CAR_NAMES VALUES (225, 'buick', 'buick opel isuzu deluxe');
INSERT INTO CAR_NAMES VALUES (226, 'renault', 'renault 5 gtl');
INSERT INTO CAR_NAMES VALUES (227, 'plymouth', 'plymouth arrow gs');
INSERT INTO CAR_NAMES VALUES (228, 'datsun', 'datsun f-10 hatchback');
INSERT INTO CAR_NAMES VALUES (229, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO CAR_NAMES VALUES (230, 'oldsmobile', 'oldsmobile cutlass supreme');
INSERT INTO CAR_NAMES VALUES (231, 'dodge', 'dodge monaco brougham');
INSERT INTO CAR_NAMES VALUES (232, 'mercury', 'mercury cougar brougham');
INSERT INTO CAR_NAMES VALUES (233, 'chevrolet', 'chevrolet concours');
INSERT INTO CAR_NAMES VALUES (234, 'buick', 'buick skylark');
INSERT INTO CAR_NAMES VALUES (235, 'plymouth', 'plymouth volare custom');
INSERT INTO CAR_NAMES VALUES (236, 'ford', 'ford granada');
INSERT INTO CAR_NAMES VALUES (237, 'pontiac', 'pontiac grand prix lj');
INSERT INTO CAR_NAMES VALUES (238, 'chevrolet', 'chevrolet monte carlo landau');
INSERT INTO CAR_NAMES VALUES (239, 'chrysler', 'chrysler cordoba');
INSERT INTO CAR_NAMES VALUES (240, 'ford', 'ford thunderbird');
INSERT INTO CAR_NAMES VALUES (241, 'volkswagen', 'volkswagen rabbit custom');
INSERT INTO CAR_NAMES VALUES (242, 'pontiac', 'pontiac sunbird coupe');
INSERT INTO CAR_NAMES VALUES (243, 'toyota', 'toyota corolla liftback');
INSERT INTO CAR_NAMES VALUES (244, 'ford', 'ford mustang ii 2+2');
INSERT INTO CAR_NAMES VALUES (245, 'chevrolet', 'chevrolet chevette');
INSERT INTO CAR_NAMES VALUES (246, 'dodge', 'dodge colt m/m');
INSERT INTO CAR_NAMES VALUES (247, 'subaru', 'subaru dl');
INSERT INTO CAR_NAMES VALUES (248, 'volkswagen', 'volkswagen dasher');
INSERT INTO CAR_NAMES VALUES (249, 'datsun', 'datsun 810');
INSERT INTO CAR_NAMES VALUES (250, 'bmw', 'bmw 320i');
INSERT INTO CAR_NAMES VALUES (251, 'mazda', 'mazda rx-4');
INSERT INTO CAR_NAMES VALUES (252, 'volkswagen', 'volkswagen rabbit custom diesel');
INSERT INTO CAR_NAMES VALUES (253, 'ford', 'ford fiesta');
INSERT INTO CAR_NAMES VALUES (254, 'mazda', 'mazda glc deluxe');
INSERT INTO CAR_NAMES VALUES (255, 'datsun', 'datsun b210 gx');
INSERT INTO CAR_NAMES VALUES (256, 'honda', 'honda civic cvcc');
INSERT INTO CAR_NAMES VALUES (257, 'oldsmobile', 'oldsmobile cutlass salon brougham');
INSERT INTO CAR_NAMES VALUES (258, 'dodge', 'dodge diplomat');
INSERT INTO CAR_NAMES VALUES (259, 'mercury', 'mercury monarch ghia');
INSERT INTO CAR_NAMES VALUES (260, 'pontiac', 'pontiac phoenix lj');
INSERT INTO CAR_NAMES VALUES (261, 'chevrolet', 'chevrolet malibu');
INSERT INTO CAR_NAMES VALUES (262, 'ford', 'ford fairmont (auto)');
INSERT INTO CAR_NAMES VALUES (263, 'ford', 'ford fairmont (man)');
INSERT INTO CAR_NAMES VALUES (264, 'plymouth', 'plymouth volare');
INSERT INTO CAR_NAMES VALUES (265, 'amc', 'amc concord');
INSERT INTO CAR_NAMES VALUES (266, 'buick', 'buick century special');
INSERT INTO CAR_NAMES VALUES (267, 'mercury', 'mercury zephyr');
INSERT INTO CAR_NAMES VALUES (268, 'dodge', 'dodge aspen');
INSERT INTO CAR_NAMES VALUES (269, 'amc', 'amc concord d/l');
INSERT INTO CAR_NAMES VALUES (270, 'chevrolet', 'chevrolet monte carlo landau');
INSERT INTO CAR_NAMES VALUES (271, 'buick', 'buick regal sport coupe (turbo)');
INSERT INTO CAR_NAMES VALUES (272, 'ford', 'ford futura');
INSERT INTO CAR_NAMES VALUES (273, 'dodge', 'dodge magnum xe');
INSERT INTO CAR_NAMES VALUES (274, 'chevrolet', 'chevrolet chevette');
INSERT INTO CAR_NAMES VALUES (275, 'toyota', 'toyota corona');
INSERT INTO CAR_NAMES VALUES (276, 'datsun', 'datsun 510');
INSERT INTO CAR_NAMES VALUES (277, 'dodge', 'dodge omni');
INSERT INTO CAR_NAMES VALUES (278, 'toyota', 'toyota celica gt liftback');
INSERT INTO CAR_NAMES VALUES (279, 'plymouth', 'plymouth sapporo');
INSERT INTO CAR_NAMES VALUES (280, 'oldsmobile', 'oldsmobile starfire sx');
INSERT INTO CAR_NAMES VALUES (281, 'datsun', 'datsun 200-sx');
INSERT INTO CAR_NAMES VALUES (282, 'audi', 'audi 5000');
INSERT INTO CAR_NAMES VALUES (283, 'volvo', 'volvo 264gl');
INSERT INTO CAR_NAMES VALUES (284, 'saab', 'saab 99gle');
INSERT INTO CAR_NAMES VALUES (285, 'peugeot', 'peugeot 604sl');
INSERT INTO CAR_NAMES VALUES (286, 'volkswagen', 'volkswagen scirocco');
INSERT INTO CAR_NAMES VALUES (287, 'honda', 'honda accord lx');
INSERT INTO CAR_NAMES VALUES (288, 'pontiac', 'pontiac lemans v6');
INSERT INTO CAR_NAMES VALUES (289, 'mercury', 'mercury zephyr 6');
INSERT INTO CAR_NAMES VALUES (290, 'ford', 'ford fairmont 4');
INSERT INTO CAR_NAMES VALUES (291, 'amc', 'amc concord dl 6');
INSERT INTO CAR_NAMES VALUES (292, 'dodge', 'dodge aspen 6');
INSERT INTO CAR_NAMES VALUES (293, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO CAR_NAMES VALUES (294, 'ford', 'ford ltd landau');
INSERT INTO CAR_NAMES VALUES (295, 'mercury', 'mercury grand marquis');
INSERT INTO CAR_NAMES VALUES (296, 'dodge', 'dodge st. regis');
INSERT INTO CAR_NAMES VALUES (297, 'buick', 'buick estate wagon (sw)');
INSERT INTO CAR_NAMES VALUES (298, 'ford', 'ford country squire (sw)');
INSERT INTO CAR_NAMES VALUES (299, 'chevrolet', 'chevrolet malibu classic (sw)');
INSERT INTO CAR_NAMES VALUES (300, 'chrysler', 'chrysler lebaron town @ country (sw)');
INSERT INTO CAR_NAMES VALUES (301, 'volkswagen', 'vw rabbit custom');
INSERT INTO CAR_NAMES VALUES (302, 'mazda',  'mazda glc deluxe');
INSERT INTO CAR_NAMES VALUES (303, 'dodge', 'dodge colt hatchback custom');
INSERT INTO CAR_NAMES VALUES (304, 'amc', 'amc spirit dl');
INSERT INTO CAR_NAMES VALUES (305, 'mercedes', 'mercedes benz 300d');
INSERT INTO CAR_NAMES VALUES (306, 'cadillac', 'cadillac eldorado');
INSERT INTO CAR_NAMES VALUES (307, 'peugeot', 'peugeot 504');
INSERT INTO CAR_NAMES VALUES (308, 'oldsmobile', 'oldsmobile cutlass salon brougham');
INSERT INTO CAR_NAMES VALUES (309, 'plymouth', 'plymouth horizon');
INSERT INTO CAR_NAMES VALUES (310, 'plymouth', 'plymouth horizon tc3');
INSERT INTO CAR_NAMES VALUES (311, 'datsun', 'datsun 210');
INSERT INTO CAR_NAMES VALUES (312, 'fiat', 'fiat strada custom');
INSERT INTO CAR_NAMES VALUES (313, 'buick', 'buick skylark limited');
INSERT INTO CAR_NAMES VALUES (314, 'chevrolet', 'chevrolet citation');
INSERT INTO CAR_NAMES VALUES (315, 'oldsmobile', 'oldsmobile omega brougham');
INSERT INTO CAR_NAMES VALUES (316, 'pontiac', 'pontiac phoenix');
INSERT INTO CAR_NAMES VALUES (317, 'volkswagen', 'vw rabbit');
INSERT INTO CAR_NAMES VALUES (318, 'toyota', 'toyota corolla tercel');
INSERT INTO CAR_NAMES VALUES (319, 'chevrolet', 'chevrolet chevette');
INSERT INTO CAR_NAMES VALUES (320, 'datsun', 'datsun 310');
INSERT INTO CAR_NAMES VALUES (321, 'chevrolet', 'chevrolet citation');
INSERT INTO CAR_NAMES VALUES (322, 'ford', 'ford fairmont');
INSERT INTO CAR_NAMES VALUES (323, 'amc', 'amc concord');
INSERT INTO CAR_NAMES VALUES (324, 'dodge', 'dodge aspen');
INSERT INTO CAR_NAMES VALUES (325, 'audi', 'audi 4000');
INSERT INTO CAR_NAMES VALUES (326, 'toyota', 'toyota corona liftback');
INSERT INTO CAR_NAMES VALUES (327, 'mazda', 'mazda 626');
INSERT INTO CAR_NAMES VALUES (328, 'datsun', 'datsun 510 hatchback');
INSERT INTO CAR_NAMES VALUES (329, 'toyota', 'toyota corolla');
INSERT INTO CAR_NAMES VALUES (330, 'mazda', 'mazda glc');
INSERT INTO CAR_NAMES VALUES (331, 'dodge', 'dodge colt');
INSERT INTO CAR_NAMES VALUES (332, 'datsun', 'datsun 210');
INSERT INTO CAR_NAMES VALUES (333, 'volkswagen', 'vw rabbit c (diesel)');
INSERT INTO CAR_NAMES VALUES (334, 'volkswagen', 'vw dasher (diesel)');
INSERT INTO CAR_NAMES VALUES (335, 'audi', 'audi 5000s (diesel)');
INSERT INTO CAR_NAMES VALUES (336, 'mercedes-benz', 'mercedes-benz 240d');
INSERT INTO CAR_NAMES VALUES (337, 'honda', 'honda civic 1500 gl');
INSERT INTO CAR_NAMES VALUES (338, 'renault', 'renault lecar deluxe');
INSERT INTO CAR_NAMES VALUES (339, 'subaru', 'subaru dl');
INSERT INTO CAR_NAMES VALUES (340,  'volkswagen', 'volkswagen rabbit');
INSERT INTO CAR_NAMES VALUES (341, 'datsun', 'datsun 280-zx');
INSERT INTO CAR_NAMES VALUES (342, 'mazda', 'mazda rx-7 gs');
INSERT INTO CAR_NAMES VALUES (343, 'triumph', 'triumph tr7 coupe');
INSERT INTO CAR_NAMES VALUES (344, 'ford', 'ford mustang cobra');
INSERT INTO CAR_NAMES VALUES (345, 'honda', 'honda accord');
INSERT INTO CAR_NAMES VALUES (346, 'plymouth', 'plymouth reliant');
INSERT INTO CAR_NAMES VALUES (347, 'buick', 'buick skylark');
INSERT INTO CAR_NAMES VALUES (348, 'dodge', 'dodge aries wagon (sw)');
INSERT INTO CAR_NAMES VALUES (349, 'chevrolet', 'chevrolet citation');
INSERT INTO CAR_NAMES VALUES (350, 'plymouth', 'plymouth reliant');
INSERT INTO CAR_NAMES VALUES (351, 'toyota', 'toyota starlet');
INSERT INTO CAR_NAMES VALUES (352, 'plymouth', 'plymouth champ');
INSERT INTO CAR_NAMES VALUES (353, 'honda', 'honda civic 1300');
INSERT INTO CAR_NAMES VALUES (354, 'subaru', 'subaru');
INSERT INTO CAR_NAMES VALUES (355, 'datsun', 'datsun 210 mpg');
INSERT INTO CAR_NAMES VALUES (356, 'toyota', 'toyota tercel');
INSERT INTO CAR_NAMES VALUES (357, 'mazda', 'mazda glc 4');
INSERT INTO CAR_NAMES VALUES (358, 'plymouth', 'plymouth horizon 4');
INSERT INTO CAR_NAMES VALUES (359, 'ford', 'ford escort 4w');
INSERT INTO CAR_NAMES VALUES (360, 'ford', 'ford escort 2h');
INSERT INTO CAR_NAMES VALUES (361, 'volkswagen', 'volkswagen jetta');
INSERT INTO CAR_NAMES VALUES (362, 'renault', 'renault 18i');
INSERT INTO CAR_NAMES VALUES (363, 'honda', 'honda prelude');
INSERT INTO CAR_NAMES VALUES (364, 'toyota', 'toyota corolla');
INSERT INTO CAR_NAMES VALUES (365, 'datsun', 'datsun 200sx');
INSERT INTO CAR_NAMES VALUES (366, 'mazda', 'mazda 626');
INSERT INTO CAR_NAMES VALUES (367, 'peugeot', 'peugeot 505s turbo diesel');
INSERT INTO CAR_NAMES VALUES (368, 'saab', 'saab 900s');
INSERT INTO CAR_NAMES VALUES (369, 'volvo', 'volvo diesel');
INSERT INTO CAR_NAMES VALUES (370, 'toyota', 'toyota cressida');
INSERT INTO CAR_NAMES VALUES (371, 'datsun', 'datsun 810 maxima');
INSERT INTO CAR_NAMES VALUES (372, 'buick', 'buick century');
INSERT INTO CAR_NAMES VALUES (373, 'oldsmobile', 'oldsmobile cutlass ls');
INSERT INTO CAR_NAMES VALUES (374, 'ford', 'ford granada gl');
INSERT INTO CAR_NAMES VALUES (375, 'chrysler', 'chrysler lebaron salon');
INSERT INTO CAR_NAMES VALUES (376, 'chevrolet', 'chevrolet cavalier');
INSERT INTO CAR_NAMES VALUES (377, 'chevrolet', 'chevrolet cavalier wagon');
INSERT INTO CAR_NAMES VALUES (378, 'chevrolet', 'chevrolet cavalier 2-door');
INSERT INTO CAR_NAMES VALUES (379, 'pontiac', 'pontiac j2000 se hatchback');
INSERT INTO CAR_NAMES VALUES (380, 'dodge', 'dodge aries se');
INSERT INTO CAR_NAMES VALUES (381, 'pontiac', 'pontiac phoenix');
INSERT INTO CAR_NAMES VALUES (382, 'ford', 'ford fairmont futura');
INSERT INTO CAR_NAMES VALUES (383, 'amc', 'amc concord dl');
INSERT INTO CAR_NAMES VALUES (384, 'volkswagen', 'volkswagen rabbit l');
INSERT INTO CAR_NAMES VALUES (385, 'mazda', 'mazda glc custom l');
INSERT INTO CAR_NAMES VALUES (386, 'mazda', 'mazda glc custom');
INSERT INTO CAR_NAMES VALUES (387, 'plymouth', 'plymouth horizon miser');
INSERT INTO CAR_NAMES VALUES (388, 'mercury', 'mercury lynx l');
INSERT INTO CAR_NAMES VALUES (389, 'nissan', 'nissan stanza xe');
INSERT INTO CAR_NAMES VALUES (390, 'honda', 'honda accord');
INSERT INTO CAR_NAMES VALUES (391, 'toyota', 'toyota corolla');
INSERT INTO CAR_NAMES VALUES (392, 'honda', 'honda civic');
INSERT INTO CAR_NAMES VALUES (393, 'honda', 'honda civic (auto)');
INSERT INTO CAR_NAMES VALUES (394, 'datsun', 'datsun 310 gx');
INSERT INTO CAR_NAMES VALUES (395, 'buick', 'buick century limited');
INSERT INTO CAR_NAMES VALUES (396, 'oldsmobile', 'oldsmobile cutlass ciera (diesel)');
INSERT INTO CAR_NAMES VALUES (397, 'chrysler', 'chrysler lebaron medallion');
INSERT INTO CAR_NAMES VALUES (398, 'ford', 'ford granada l');
INSERT INTO CAR_NAMES VALUES (399, 'toyota', 'toyota celica gt');
INSERT INTO CAR_NAMES VALUES (400, 'dodge', 'dodge charger 2.2');
INSERT INTO CAR_NAMES VALUES (401, 'chevrolet', 'chevrolet camaro');
INSERT INTO CAR_NAMES VALUES (402, 'ford', 'ford mustang gl');
INSERT INTO CAR_NAMES VALUES (403, 'volkswagen', 'vw pickup');
INSERT INTO CAR_NAMES VALUES (404, 'dodge', 'dodge rampage');
INSERT INTO CAR_NAMES VALUES (405, 'ford', 'ford ranger');
INSERT INTO CAR_NAMES VALUES (406, 'chevrolet', 'chevy s-10');
