INSERT INTO GRAPES VALUES (1, 'Barbera', 'Red');
INSERT INTO GRAPES VALUES (2, 'Cabernet Franc', 'Red');
INSERT INTO GRAPES VALUES (3, 'Cabernet Sauvingnon', 'Red');
INSERT INTO GRAPES VALUES (4, 'Chardonnay', 'White');
INSERT INTO GRAPES VALUES (5, 'Grenache', 'Red');
INSERT INTO GRAPES VALUES (6, 'Malbec', 'Red');
INSERT INTO GRAPES VALUES (7, 'Marsanne', 'White');
INSERT INTO GRAPES VALUES (8, 'Merlot', 'Red');
INSERT INTO GRAPES VALUES (9, 'Mourvedre', 'Red');
INSERT INTO GRAPES VALUES (10, 'Muscat', 'White');
INSERT INTO GRAPES VALUES (11, 'Petite Sirah', 'Red');
INSERT INTO GRAPES VALUES (12, 'Pinot Noir', 'Red');
INSERT INTO GRAPES VALUES (13, 'Riesling', 'White');
INSERT INTO GRAPES VALUES (14, 'Roussanne', 'White');
INSERT INTO GRAPES VALUES (15, 'Sangiovese', 'Red');
INSERT INTO GRAPES VALUES (16, 'Sauvignon Blanc', 'White');
INSERT INTO GRAPES VALUES (17, 'Syrah', 'Red');
INSERT INTO GRAPES VALUES (18, 'Tempranillo', 'Red');
INSERT INTO GRAPES VALUES (19, 'Viognier', 'White');
INSERT INTO GRAPES VALUES (20, 'Zinfandel', 'Red');
